### ISSUE TITLE
Is this stil working?

### ISSUE THREAD

**Issue by bafplus** [nk932714/yify-movies-php#25]
Sinse the complete https://yts.ag seems down or corrupted (from my end) and i cant seem to get this repo working.
Is it just me?

**Comment by bafplus** [comment]
i get this warning:
Notice: Trying to get property of non-object in C:\Users\bartc\Desktop\USBWebserver v8.6\root\index.php on line 151

Notice: Trying to get property of non-object in C:\Users\bartc\Desktop\USBWebserver v8.6\root\index.php on line 151

Fatal error: Uncaught exception 'Exception' with message 'API request failed. Error was: ' in /pathtoroot\index.php:151 Stack trace: #0 pathtoroot\index.php(47): YTS->getFromApi('https://yts.ag/...') #1 pathtoroot\index.php(26): YTS->listMovies('', 20, 1, '', '', '', '') #2 {main} thrown in pathtoroot\index.php on line 151

**Comment by bafplus** [comment]
Nevermind,....its me...used the 000webhost way and that worked...still some php errors tho:

Warning: count(): Parameter must be an array or an object that implements Countable in /storage/ssd3/230/10321230/public_html/index.php on line 176

Warning: count(): Parameter must be an array or an object that implements Countable in /storage/ssd3/230/10321230/public_html/index.php on line 176

Warning: count(): Parameter must be an array or an object that implements Countable in /storage/ssd3/230/10321230/public_html/index.php on line 176

Warning: count(): Parameter must be an array or an object that implements Countable in /storage/ssd3/230/10321230/public_html/index.php on line 176

Warning: count(): Parameter must be an array or an object that implements Countable in /storage/ssd3/230/10321230/public_html/index.php on line 176

Warning: count(): Parameter must be an array or an object that implements Countable in /storage/ssd3/230/10321230/public_html/index.php on line 176

Warning: count(): Parameter must be an array or an object that implements Countable in /storage/ssd3/230/10321230/public_html/index.php on line 176
...........

**Comment by bafplus** [comment]
fixed! Had to select the correct php version since it standard is on php7.
selecting php 5.7 did the trick, all lower versions still had issues.

Maybe add this instruction in the readme in the 00webhost paragraph.

**Comment by nk932714** [comment]
> 
> 
> fixed! Had to select the correct php version since it standard is on php7.
> selecting php 5.7 did the trick, all lower versions still had issues.
> 
> Maybe add this instruction in the readme in the 00webhost paragraph.

Thanks i'll add

**Comment by nk932714** [comment]
added and yes its working fine.
