### ISSUE TITLE
Unable to list movies using actor name as query_term

### ISSUE THREAD

**Issue by ilman** [nk932714/yify-movies-php#30]
Hi, First of all thanks for creating this nice project!

I have tried to clone your repo and its pretty much working fine. Though I cant seem to list movies when i search using actor name? 

Is it bug or yify api related issue?

Best Regards

**Comment by nk932714** [comment]
@ilman , currently i'm busy with my work, but whenever i'll get the time, i'll check this issue, 

As far now i checked the api with actors name and got zero results however i checked the same name on yify website and got list of movies. So this might be possible that there is bug in api,

**Comment by nk932714** [comment]
unfortunately, its API issue. I can fix this by using scraping the website  but that will increase the load on yify official website. so for now i'm not implementing this. Hope they will fix their api issue soon.
