### ISSUE TITLE
subtitle not found

### ISSUE THREAD

**Issue by aouniradouan** [nk932714/yify-movies-php#35]
the old website has been removed this is the new one https://yts-subs.com/movie-imdb/ but it not work can you help please with new code ? thank you

**Comment by nk932714** [comment]
Thanks for notifying @aouniradouan 
yts-subs seems to be an fake website,
yifytorrents.org is the new website i believe.

**Comment by nk932714** [comment]
now its fixed 👍

**Comment by aouniradouan** [comment]
> now its fixed 👍

Thank you, it's work fine 💯
