### ISSUE TITLE
Showing Popads

### ISSUE THREAD

**Issue by xcoders-hub** [nk932714/yify-movies-php#36]
When try to stream torrent it shows popads inside player. How to fix this?

**Comment by nk932714** [comment]
already mentioned this in readme 
![image](https://user-images.githubusercontent.com/29853208/100048151-2c3b5980-2e3a-11eb-8ba3-a5b88946b682.png)

Popup ads is being displayed by webtor(streaming website). Can be skiped by simply installing adblocker in browser.

However there is a alternative of webtor which have no ads is **magnet-player** but it is not efficient as webtor

**Comment by xcoders-hub** [comment]
Which magnet player you didn't mention?
